### ISSUE TITLE
Action (User Input)

### ISSUE THREAD

**Issue by its-felipe-almeida** [Eclair/CircleProgressBar#19]
Can I have an action click event on the circle progress?

**Comment by Eclair** [comment]
Hi @felipeaugusto1,

The control itself doesn't have it, because it was designed as `ProgressBar` to display things without any user input. 

If you need simple touch events - I believe you can put a transparent `UIButton` just on top of progress bar, or even use `UITapGestureRecognizer` that targets `CircleProgressBarView`.
If that's not what you need, and you still need user ability to set progress manually with your finger - you need some kind of `Slider` instead of `ProgressBar`...

Let me know if you have any questions.

Kind Regards,
