### ISSUE TITLE
Progress Duration is Wrong

### ISSUE THREAD

**Issue by bchessin** [Eclair/CircleProgressBar#20]
Try doing setProgress: 1 duration:30.0f, the bar will only get to about 90% in the demo app (also experiences the same in my app). Is there a fix for this?

**Comment by Eclair** [comment]
Just tested the latest version with your code:

```
[_circleProgressBar setProgress:1 animated:YES duration:30];
```

It works just fine for me. Are you sure nothing stops the animation from another place?

Also the duration seems kinda long to me, if you synchronizing it with audio/video playback or some timer - I would recommend you to set up your own timer and update progressbar from there, because here you will have more control on the situation.

**Comment by Eclair** [comment]
**Update:**

```
[_circleProgressBar setProgress:1 animated:YES duration:30.0f];
```

Works the same way...

**Comment by Eclair** [comment]
So yep, I still unable to reproduce this issue you facing. Try to make a new project from scratch, import CircleProgressBar and run your code in clean environment. I believe you can experience such a problem because of some other code (maybe you're doing too much in main application thread?)

**Comment by Eclair** [comment]
@bchessin Let me know if you find a way to 100% reproduce this issue, so I can help you with it

**Comment by bchessin** [comment]
I emailed you this as well, but this sample project (which was downloaded straight from Github first) shows the issue at hand.

[CircleProgressBar-master 2.zip](https://github.com/Eclair/CircleProgressBar/files/1082196/CircleProgressBar-master.2.zip)

**Comment by bchessin** [comment]
Any progress on this issue?
