### ISSUE TITLE
How to handle animation completion?

### ISSUE THREAD

**Issue by zulkarnain-shah** [Eclair/CircleProgressBar#23]
I don't see any completion handlers that we can use when the animation completes. How to achieve that? Is there a method I'm missing ?

**Comment by Eclair** [comment]
Hi @zulkarnain-shah,

There is no such callback. If you look closely to standard iOS ProgressView: https://developer.apple.com/documentation/uikit/uiprogressview, it doesn't have it either.
The idea is to have this control only to present things, and because you are in full control of what it is presenting - you can wait for time it ends animation and then execute your specific instructions.

Thanks,

**Comment by zulkarnain-shah** [comment]
I actually found a solution to that. In the callback handler of the method **circleProgressBar.setHintTextGenerationBlock**, I check when the **progress == 1.0** then i do stuff that I need to do. A progress value of 1.0 means that animation has completed! Voila !

**Comment by Eclair** [comment]
Hehe, Well, if that's what you prefer ^_^
Usually I would separate presentation logic from business logic, because this is just a visual control, and it should not block other application logic.

**Comment by zulkarnain-shah** [comment]
It does the job for me. And its the correct calculation of the progress as well, isn't it ?

**Comment by Eclair** [comment]
@zulkarnain-shah 
Yeah, that's true.
Don't get me wrong, it's just the source of this data. For example in this case, this updates comes like this: 

**progress set outside** -> **internal timer** -> **animation** -> **callback**

And if **timer** or **animation** step in this chain would change - you can get wrong results in the callback. So instead of relying on last part of this chain, you can define everything outside (in your controller).

for example:
```
[_progressBar setProgress:0.5f animated:YES duration:0.5f];
// you timer that will fire after 0.5f (when animation should complete already)
// but it will be more reliable that UI element that just used to display things
```

To follow Single Responsibility Principle.
