### ISSUE TITLE
CircleProgressBar doesn't update progress value when animated change method is called very often

### ISSUE THREAD

**Issue by afiq90** [Eclair/CircleProgressBar#7]
Anyone know why it doesn't working in block? I tried to show this CircleProgressBar when user tapped on download button. here is my code : 
- (IBAction)DownloadButtonTapped:(id)sender {
  
  [VideoDownloaderHelper downloadVideoFromURL:@"https://fbcdn-video-n-a.akamaihd.net/hvideo-ak-xap1/v/t43.1792-2/12326419_567683906728653_1549711566_n.mp4?efg=eyJybHIiOjE1MDAsInJsYSI6MTc5OSwidmVuY29kZV90YWciOiJzdmVfaGQifQ%3D%3D&rl=1500&vabr=861&oh=39b5e0b02bb7873b2f1f7e3ec6e90d67&oe=566AD689&__gda__=1449842290_0e0e2f200458c7a7aff7f1e7acaea79e" withProgress:^(CGFloat progress) {
      NSLog(@"total progress : %f", progress);
  
    //  [_circleProgressBar setProgress:progress animated:YES];
  
  ```
  [_circleProgressBar setProgress:(_circleProgressBar.progress + progress) animated:YES];
  ```
  
  } completion:^(NSURL *filePath) {
      NSLog(@"filePath :%@", filePath);
  } onError:^(NSError *error) {
      NSLog(@"error download video: %@", error);
  }];

}

**Comment by Eclair** [comment]
@afiq90 Hm, it looks like the problem in control implementation.
It can't properly animate changes because of very often calls in this block. 

When you call `setProgress:animated:YES` next things happen:
1. it set it's progress to initial value (`_circleProgressBar.progress`)
2. it set it's goal value to passed value (`_circleProgressBar.progress + progress`)
3. start animate using timer with calculated time step (based on Animation Duration)

So Because it call `setProgress:animated:YES` again and again very often - it can't properly perform step 3 in this sequence. And because change depends on current value

I can suggest you a few workarounds for your situation:
1. use `setProgress:animated:NO` method call instead. Progress value will be changed immediately.
2. try to use `setProgress:animated:duration:` with some small duration value.
3. try to reduce amount of calls from the block itself. For example call change method only when `progressDelta > 0.1f`, for example:

```
__block float progressDelta = 0;
[VideoDownloaderHelper downloadVideoFromURL:@"https://fbcdn-video-n-a.akamaihd.net/hvideo-ak-xap1/v/t43.1792-2/12326419_567683906728653_1549711566_n.mp4?efg=eyJybHIiOjE1MDAsInJsYSI6MTc5OSwidmVuY29kZV90YWciOiJzdmVfaGQifQ%3D%3D&rl=1500&vabr=861&oh=39b5e0b02bb7873b2f1f7e3ec6e90d67&oe=566AD689&__gda__=1449842290_0e0e2f200458c7a7aff7f1e7acaea79e" withProgress:^(CGFloat progress) {
    NSLog(@"total progress : %f", progress);
    progressDelta += progress;
    if (progressDelta > 1.0f || progress == 1) {
        [_circleProgressBar setProgress:(_circleProgressBar.progress + progress) animated:YES];
        progressDelta = 0;
    }
} completion:^(NSURL *filePath) {
    NSLog(@"filePath :%@", filePath);
} onError:^(NSError *error) {
    NSLog(@"error download video: %@", error);
}];
```

But the best way (Maybe) is to change it in control implementation. When somebody is calling `setProgress:animated:` method again in the middle of current animation - maybe we need to force update progress with the end animation value. But it will look a little awkward because of animations lack...

**Comment by afiq90** [comment]
Thank you for brief explanation. I'm gonna try it now. Btw, thanks for great library.

**Comment by Eclair** [comment]
@afiq90 Thanks )
Let me know if you'll have any problems.
I will try to make appropriate changes to `setProgress:animated:` method at the same time.

Btw, looks like you need to call
`[_circleProgressBar setProgress:progress animated:YES];`
instead of 
`[_circleProgressBar setProgress:(_circleProgressBar.progress + progress) animated:YES];`

Because based on your code, `progress` value will change from 0.0 to 1.0, so you don't need to rely on `_circleProgressBar.progress` value.

**Comment by Eclair** [comment]
@afiq90 I've added `isAnimating` property and `stopAnimation` method to be able to control an animation. Be sure you updated pod version to `0.22`:

``` ruby
pod 'CircleProgressBar', '~> 0.22'
```

And you will be able to modify your code to something like this:

``` objective-c
[VideoDownloaderHelper downloadVideoFromURL:@"https://fbcdn-video-n-a.akamaihd.net/hvideo-ak-xap1/v/t43.1792-2/12326419_567683906728653_1549711566_n.mp4?efg=eyJybHIiOjE1MDAsInJsYSI6MTc5OSwidmVuY29kZV90YWciOiJzdmVfaGQifQ%3D%3D&rl=1500&vabr=861&oh=39b5e0b02bb7873b2f1f7e3ec6e90d67&oe=566AD689&__gda__=1449842290_0e0e2f200458c7a7aff7f1e7acaea79e" withProgress:^(CGFloat progress) {
    NSLog(@"total progress : %f", progress);
    if (_circleProgressBar.isAnimating) {
        [_circleProgressBar stopAnimation];
    }
    [_circleProgressBar setProgress:progress animated:YES];
} completion:^(NSURL *filePath) {
    NSLog(@"filePath :%@", filePath);
} onError:^(NSError *error) {
    NSLog(@"error download video: %@", error);
}];
```

In this case on often progress changes - it will feel like updates without animation, but for long delays between progress update block' calls - it will perform smooth animation.

Let me know if it doesn't work for you.

Thanks

**Comment by afiq90** [comment]
thank you for your responding.
